# Header
menu: #导航栏连接
  Home: /
  # API: /API 
  # Tags: /tags
  # Category: /category
  # Archives: /archives #/archives #归档页面URL 自定义页面标题: /自定义页面URL
  About: /
  # Github: /





rss: /atom.xml #rss地址  默认即可

#feed:
#  type: atom       #feed 类型 (atom/rss2)
#  path: /atom.xml   #rss 路径
#  limit: 20        #在 rss 中最多生成的文章数(0显示所有)


#icon http://fontawesome.io/
#首页显示
article_index:
  -  title: 技术实际
     content: 区别于Google收购的Magic Leap和微软的Hololens，我们基于高通的AR引擎vofuria实现的是一种增强现实的效果，并且这项技术已经相当成熟
     icon: icon-book
  -  title: 技术实用
     content: 实现了一个傻瓜式交互的拆解和拼装的说明书，这是在普通的物体识别基础上更加深入的应用场景，在生活中当你需要拆电脑换部件的时候，拆电视机更换零件的时候，需要组装刚从宜家买回来的家具的时候，这项技术都可以很好的帮到你
     icon: icon-bolt
  -  title: 硅谷的标准
     content: 我们希望用硅谷的思维来创新，真正将前沿技术应用在现实生活中，且能实际改变人们生活，使这个世界变得更加美好 :-P
     icon: icon-lab
  -  title: 未来 - 更多功能
     content: 未来我们希望在应用中能有更多实际功能，例如厂商能够通过导入详细设计图纸或模型，以及成规格的说明书来自动生成某一产品的3D说明模型
     icon: icon-bolt



# Content
excerpt_link: Read More  #阅读更多的文字显示
# fancybox: false  #开启fancybox效果 




# Miscellaneous #社交网络和统计连接地址
baidu_analytics:  #百度统计
favicon: /css/favicon.ico 
logo: /css/logo.png
